### ISSUE TITLE
Validation fails

### ISSUE THREAD

**Issue by ajtucker** [GSS-Cogs/WG-Chargeable-homes#1]
csvlint validation is throwing up the following errors:

observations.csv is INVALID
1. unmatched_foreign_key_reference. Row: 1,2. ["1"]
2. unmatched_foreign_key_reference. Row: 2,2. ["2"]
3. unmatched_foreign_key_reference. Row: 3,2. ["3"]
4. unmatched_foreign_key_reference. Row: 4,2. ["4"]
5. unmatched_foreign_key_reference. Row: 5,2. ["5"]
6. unmatched_foreign_key_reference. Row: 6,2. ["6"]
7. unmatched_foreign_key_reference. Row: 7,2. ["7"]
8. unmatched_foreign_key_reference. Row: 8,2. ["8"]
9. unmatched_foreign_key_reference. Row: 9,2. ["9"]
10. unmatched_foreign_key_reference. Row: 10,2. ["10"]
11. unmatched_foreign_key_reference. Row: 11,2. ["11"]

**Comment by LPerryman** [comment]
Script was pulling in the column Band_Code, which holds a number reference. The codelist file council-tax-band.csv stipulates a letter. Changed column to Band_ItemName_ENG instead. 
Also mapped A- to Adash and Total to total (capital T) as defined in the codelist file.
Run the pipeline and all worked ok, all green.
